### ISSUE TITLE
跳转导航页失败

### ISSUE THREAD

**Issue by 843139231** [NextBoy/megalo-router#3]
在普通页面内进行 this.$router.push  tab页，会 报错  onReady function;at api navigateTo fail callback function。无法正确跳转至想要的 tab页。

望解决。目前采用的方案，我只能是先使用 wx.switchTab 来进行 跳转先

**Comment by NextBoy** [comment]
```
Vue.use(megaloRouter, {
  mode: 'strict', // strict or loose 可配置项，不配置的话默认为strict
  tabBars: [ // 必须配置项
    '/pages/hello',
    '/pages/my/index'
  ]
})
```
你应该没有配置tab到这里
